### ISSUE TITLE
一个十连内出现两个相同物品会导致无法导入

### ISSUE THREAD

**Issue by sunfkny** [Scighost/KeqingNiuza#1]
![image](https://user-images.githubusercontent.com/30853461/116349667-15eb5c80-a823-11eb-8a84-d81b42f6e1a9.png)

**Comment by Scighost** [comment]
问题已收到，我先简述一下导入数据匹配现有数据的算法。
导入数据按Excel表格顺序排列，现有数据按id排列，以现有数据首项的抽卡时间为节点，逐一比对此时间点之后的数据，到表格末尾为止，如果出现时间或名称对不上的情况，则会显示与原始数据不匹配。

你可以去“原始数据”页面找到这个时间点的记录，手动和导入数据对比一下。
可能是因为之前版本保存数据时会把24小时制变为12小时制（我的失误），在原始数据中也可以查到，需要清空UserData文件夹再重新加载。
如果还是没办法确定问题，那就麻烦把文件发到我的邮箱 scighost@outlook.com，我再仔细看看。

**Comment by sunfkny** [comment]
原来是有一组十连日期顺序错了，清空UserData文件夹之后重新导入就好了
