### ISSUE TITLE
大佬，3.0更新了抽卡历史界面，好像用不了了。谢谢你的更新。

### ISSUE THREAD

**Issue by GGWON** [Scighost/KeqingNiuza#100]
如果有可能的话，大佬能不能再更新一下呢。超级感谢。如果不行就算了。非常感谢大佬的更新。

**Comment by Klamist** [comment]
PC端只能通过代理获取url，牛杂店没有这个模块，不会加了。但你可以手动获得url然后导入牛杂店里，可以去关于界面手动填写，如何获得url可以去b站搜视频。

**Comment by GGWON** [comment]
> PC端只能通过代理获取url，牛杂店没有这个模块，不会加了。但你可以手动获得url然后导入牛杂店里，可以去关于界面手动填写，如何获得url可以去b站搜视频。
好的谢谢大佬。
