### ISSUE TITLE
似乎无法更新图片卡池信息

### ISSUE THREAD

**Issue by FanJZSS** [Scighost/KeqingNiuza#102]
![QQ截图20220901132501](https://user-images.githubusercontent.com/96369018/187838387-b90d240f-fd0d-4c4f-a196-1847e12124d1.png)

这是日志文件
[keqing-220901.txt](https://github.com/xunkong/KeqingNiuza/files/9467106/keqing-220901.txt)

**Comment by Scighost** [comment]
很遗憾，牛杂店已停止维护，出现错误很正常。
