### ISSUE TITLE
希望加入自定义抽卡记录网页的选项

### ISSUE THREAD

**Issue by Lparksi** [Scighost/KeqingNiuza#11]
当前版本必须要pc端安装原神才能够使用，我认为可以增加一个选项让用户输入Url来获取相关的信息，不必要再安装一个原神（手机、PS、云游戏）会相对更实用一点。谢谢

**Comment by Scighost** [comment]
建议已收到，这个需求不是很急迫，先搁置下来

**Comment by Lparksi** [comment]
顺便问一下，这算bug吗（武器图片展示补全）
![image](https://user-images.githubusercontent.com/60086490/129432546-e574523f-3a83-4e78-abd5-ba653940c18f.png)

**Comment by Scighost** [comment]
不是Bug，Wiki里的原图就是这样

**Comment by Lparksi** [comment]
了解了

**Comment by Scighost** [comment]
已更新
![image](https://user-images.githubusercontent.com/61003590/131301452-89a4fdd0-0fd6-40de-b4a1-d4bb5099e5e8.png)
