### ISSUE TITLE
HTTP 401

### ISSUE THREAD

**Issue by qwuae1** [Scighost/KeqingNiuza#12]
![image](https://user-images.githubusercontent.com/36930393/130268308-38f34a71-c956-46e4-97ce-7c78f0007b39.png)
https://dav.jianguoyun.com/dav/
这个服务器地址不对嘛
才注册的账号
密码不会不对吧
用户名一栏填了用户名和邮箱，两个都401
还是云备份已经无了

**Comment by Scighost** [comment]
应该是没问题的，这里的密码不是账户密码，而是应用密码，详见关于页面
