### ISSUE TITLE
点击成就，在成就页面程序无反应

### ISSUE THREAD

**Issue by JesseMcccree** [Scighost/KeqingNiuza#14]
如题，该如何解决

**Comment by Scighost** [comment]
似乎知道问题发生在哪儿了，但是不确定。
问你一下，你的抽卡记录按照时间分布只有一天吗？

**Comment by JesseMcccree** [comment]
抽卡记录显示正常

**Comment by JesseMcccree** [comment]
抽卡有两天

**Comment by Scighost** [comment]
新发布了一个版本，你试一下修复了没。
[下载地址 (有效期1小时)](https://xunkong-1306705684.cos.ap-shanghai.myqcloud.com/share/KeqingNiuza.zip?q-sign-algorithm=sha1&q-ak=AKID4pRpEeJc7Jd9_TcL_5aFc0nArZa-OEQ2k2FmgnNV4elPWQnKVYa_jRjqJGV0elik&q-sign-time=1629726910;1629730510&q-key-time=1629726910;1629730510&q-header-list=&q-url-param-list=&q-signature=63ff0ef90f9422b8bf39c476b604bb7dbf436793&x-cos-security-token=igeca90WY42Rw3xUQ0MmFEaQ8malGjAa2f4f03c6804b2d8667977f6d4c9b3af1YCzGiD0Ywqxb8VTf_taTKDeJyBtDEQxarBqVXIzv92wRuReLRLU8ClRAnekwmIWlHsEWf8fux6058MdxLKhzumxcF9k0rz6lsRVBqQ65OoreYg5UN01tV_jOWmmXxtucQHHCzWEWO7deH0x-7sS4Sb6Pf1LS2TGlDFWbuWNPcHQ)

**Comment by JesseMcccree** [comment]
![屏幕截图(72)](https://user-images.githubusercontent.com/87928575/130461175-298e4e14-6233-4319-944c-14de570e5863.png)
修复了，是只显示这两个吗？

**Comment by Scighost** [comment]
OK，没问题了

**Comment by JesseMcccree** [comment]
非常感谢
