### ISSUE TITLE
首次加载数据后出错

### ISSUE THREAD

**Issue by Lightczx** [Scighost/KeqingNiuza#15]
UserData里明明是有数据的但仍报错
`TaergetInvocationException`:调用的目标发生了异常
`NullReferenceException`:没有数据

**Comment by Lightczx** [comment]
开着VPN加载速度慢就会遇到这个bug，关了vpn加载速度快了就没问题

**Comment by Lightczx** [comment]
是在请求祈愿记录完成的时候资源还没下载完导致的
最好可以首次下载资源的时候禁止请求祈愿记录或者跳转其他页面

**Comment by Scighost** [comment]
软件打开的时候如果没有UserData文件夹会跳转到有下载进度的介绍页面；
我在软件包里附带了必要的数据资源，后下载的图片对程序逻辑没有影响；
更新卡池信息后可能没更新软件包，会出现这种情况。

**Comment by Lightczx** [comment]
如何修复这个问题呢

**Comment by Lightczx** [comment]
一次打开报错后次次都报错了

**Comment by Scighost** [comment]
每次都报错？有可能是本地资源没更新或者我的卡池时间统计错了
有调用堆栈就把调用堆栈发一下

**Comment by Lightczx** [comment]
用了新的资源文件之后就好了
