### ISSUE TITLE
群晖使用webdav还原数据提示 登录失败:Method Not Allowed(405)

### ISSUE THREAD

**Issue by MageMaize** [Scighost/KeqingNiuza#16]
在家里的群晖NAS上启动了一个WebDav服务器，在内网是能用的。但是在外网换了一台电脑后，登录时无法使用，弹出登录失败:Method Not Allowed(405)提示。

可以确认NAS的端口都是开启的，防火墙，端口转发均已正确配置，使用windows资源管理器自带的添加网络位置可以正常连接webdav服务器，打开备份文件。

**Comment by Scighost** [comment]
不懂，我对网络知识一窍不通

**Comment by MageMaize** [comment]
行吧，之后我自己换了个webdav服务也能凑合用，可能是群晖的东西有点小毛病，感谢回复。
