### ISSUE TITLE
2.0版本启动很慢

### ISSUE THREAD

**Issue by du2333** [Scighost/KeqingNiuza#17]
启动检查更新要半天，是海外的网络

**Comment by Scighost** [comment]
等我配置一个cdn，应该会快些

**Comment by Scighost** [comment]
新的启动器下载地址，也可以在原有启动器上更新。
[传送门](https://xw6dp97kei-1306705684.file.myqcloud.com/keqingniuza/meta/KeqingNiuza.zip)

**Comment by du2333** [comment]
确实快了好多，感谢作者！
