### ISSUE TITLE
有一个小小的请求，新增一个删除祈愿记录或者从指定祈愿开始计算祈愿数据的功能

### ISSUE THREAD

**Issue by ishkong** [Scighost/KeqingNiuza#21]
首先感谢作者提供这个优秀的软件

我有个小小的请求，增加一个删除祈愿或者从指定时间开始计算祈愿数据的功能

理由：
由于缺失6个月之前的记录，导致我能获取到的第一个角色祈愿的记录不准确。因此希望能够增加一个删除部分祈愿或者从某次祈愿开始计算祈愿的功能，这样可以是统计数据及概率更加准确。例如，让用户选择或输入从某个祈愿ID开始计算祈愿数据。

再次感谢作者完成这个软件

**Comment by Scighost** [comment]
![image](https://user-images.githubusercontent.com/61003590/134443675-87bde2ee-3a6d-4a62-b73f-f34be32ab0b1.png)
