### ISSUE TITLE
求适配win7

### ISSUE THREAD

**Issue by wuguxi5** [Scighost/KeqingNiuza#23]

**Comment by wuguxi5** [comment]
好的，谢谢

**Comment by Scighost** [comment]
你这个问题挺有意思，[文档上](https://docs.microsoft.com/zh-cn/dotnet/api/system.net.http.httpclient.getbytearrayasync?view=netframework-4.8)提到了没有TaskCanceledException异常，但你又的确碰到了。
可能是网络问题，试一试[这个检查更新的网页](https://xw6dp97kei-1306705684.file.myqcloud.com/keqingniuza/meta/version.json)能不能打开。
