### ISSUE TITLE
定时提醒功能建议加入恢复速度

### ISSUE THREAD

**Issue by sunfkny** [Scighost/KeqingNiuza#3]
现在1个"恢复间隔"回复1个，对于洞天宝钱这种回复速度是xx/小时的需要计算

建议添加一个恢复速度选项（默认为1），洞天宝钱这种情况可以修改倍率

**Comment by Scighost** [comment]
我认为这个功能没有必要，现在 恢复间隔 会改变的任务可能就只有 洞天宝钱 和 洞天赠礼，一个版本过去仙力数值也基本固定了，加一个速度选项作用不大。
