### ISSUE TITLE
实时便笺：data is not public for the user

### ISSUE THREAD

**Issue by XTsat** [Scighost/KeqingNiuza#37]
我注册完是这个data is not public for the user
还有固定磁贴在哪里固定

**Comment by Scighost** [comment]
在米游社、我的、我的角色、实时便笺 中开启数据展示；获取到数据信息后会看到固定按钮

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2021年11月2日 20:12
收件人: ***@***.***>
抄送: ***@***.***>
主题: [Scighost/KeqingNiuza] 实时便签问题 (Issue #37)


我注册完是这个data is not public for the user
还有固定磁贴在哪里固定

**Comment by XTsat** [comment]
我想起来了，我没给权限，我以为是直接获取游戏信息呢

**Comment by le0-VV** [comment]
> 我想起来了，我没给权限，我以为是直接获取游戏信息呢

我在另外一个助手App里遇到了相似的问题，请问是怎么解决的？

**Comment by XTsat** [comment]
> > 我想起来了，我没给权限，我以为是直接获取游戏信息呢
> 
> 我在另外一个助手App里遇到了相似的问题，请问是怎么解决的？

打开米游社的便签，会让你授权
