### ISSUE TITLE
添加实时便笺出现“无法找到与此错误代码关联的文本”

### ISSUE THREAD

**Issue by wuhan890809** [Scighost/KeqingNiuza#39]
老板好!
我下载了最新的客户端，设置了管理员运行。
然后按照说明导入了证书，设置了cookie，能够正确显示出树脂和派遣任务了。
但是点击固定到开始菜单的时候就报错，也没有错误代码，Log里也没有任何记录。

系统是Win10 21H1 64位企业版
截图如下
![QQ截图20211102221356](https://user-images.githubusercontent.com/15194230/139866258-d896eea7-260f-44dd-9ed4-45438dfdfd92.png)

**Comment by Scighost** [comment]
有没有出现这个窗口

**Comment by nek0us** [comment]
遇到了同样的问题，点“固定到开始屏幕”直接显示两行 “无法找到与此错误代码关联的文本”
并未出现 添加磁贴的弹窗

**Comment by nek0us** [comment]
![图片](https://user-images.githubusercontent.com/57703506/139868234-a90b80d2-f807-4511-ae90-08877e6472e7.png)

**Comment by Scighost** [comment]
单独生成了一个记录详细过程的版本，解压后覆盖 `bin` 下的文件，直接运行 `KeqingNiuza.RealtimeNotes.exe` ，日志是 `Log\note-<time>.txt` 。
下载链接 https://xw6dp97kei-1306705684.file.myqcloud.com/keqingniuza/RealtimeNotes.Trace.zip

**Comment by Scighost** [comment]
> 可以了 感谢

把怎么解决的也说一下啊😂

**Comment by wuhan890809** [comment]
我和楼上一样，用了新的RealtimeNotes.exe之后弹出了生成磁贴的提升，点了确定之后磁贴就出来了，也没有别的什么操作

**Comment by nek0us** [comment]
> 
> 
> 单独生成了一个记录详细过程的版本，解压后覆盖 `bin` 下的文件，直接运行 `KeqingNiuza.RealtimeNotes.exe` ，日志是 `Log\note-<time>.txt` 。 下载链接 [xw6dp97kei-1306705684.file.myqcloud.com/keqingniuza/RealtimeNotes.Trace.zip](https://xw6dp97kei-1306705684.file.myqcloud.com/keqingniuza/RealtimeNotes.Trace.zip)

就是用这个步骤解决的

在那之前 试过任务管理器里找到实时便笺添加管理员权限运行  没用 
删除本日日志  没有发现报错时有重新生成

在替换文件直接打开 KeqingNiuza.RealtimeNotes.exe 添加成功后 
取消磁贴 用启动器打开主程序（发现更新了6m的文件）打开实时便笺   添加磁贴 还是会报同样的错

再然后 重新直接打开KeqingNiuza.RealtimeNotes.exe 添加磁贴  报错 
重新把补丁文件覆盖bin目录后 重新打开 KeqingNiuza.RealtimeNotes.exe 添加磁贴 还是报错 
把自己试废了 
![GIF](https://user-images.githubusercontent.com/57703506/139883460-783ec783-3ba4-4e0e-bedc-c02092fafccf.gif)

**Comment by nek0us** [comment]
所以现在又用不了了 
![图片](https://user-images.githubusercontent.com/57703506/139884781-f8cfcdca-c722-4055-b708-066c57e12666.png)

**Comment by wuhan890809** [comment]
> > 单独生成了一个记录详细过程的版本，解压后覆盖 `bin` 下的文件，直接运行 `KeqingNiuza.RealtimeNotes.exe` ，日志是 `Log\note-<time>.txt` 。 下载链接 [xw6dp97kei-1306705684.file.myqcloud.com/keqingniuza/RealtimeNotes.Trace.zip](https://xw6dp97kei-1306705684.file.myqcloud.com/keqingniuza/RealtimeNotes.Trace.zip)
> 
> 就是用这个步骤解决的
> 
> 在那之前 试过任务管理器里找到实时便笺添加管理员权限运行 没用 删除本日日志 没有发现报错时有重新生成
> 
> 在替换文件直接打开 KeqingNiuza.RealtimeNotes.exe 添加成功后 取消磁贴 用启动器打开主程序（发现更新了6m的文件）打开实时便笺 添加磁贴 还是会报同样的错
> 
> 再然后 重新直接打开KeqingNiuza.RealtimeNotes.exe 添加磁贴 报错 重新把补丁文件覆盖bin目录后 重新打开 KeqingNiuza.RealtimeNotes.exe 添加磁贴 还是报错 把自己试废了 ![GIF](https://user-images.githubusercontent.com/57703506/139883460-783ec783-3ba4-4e0e-bedc-c02092fafccf.gif)

你可以试试用Dism++先把之前安装的keqing开头的appx卸载了再添加，我试了几次都是可以的

**Comment by nek0us** [comment]
> 
> 
> > > 单独生成了一个记录详细过程的版本，解压后覆盖 `bin` 下的文件，直接运行 `KeqingNiuza.RealtimeNotes.exe` ，日志是 `Log\note-<time>.txt` 。 下载链接 [xw6dp97kei-1306705684.file.myqcloud.com/keqingniuza/RealtimeNotes.Trace.zip](https://xw6dp97kei-1306705684.file.myqcloud.com/keqingniuza/RealtimeNotes.Trace.zip)
> > 
> > 
> > 就是用这个步骤解决的
> > 在那之前 试过任务管理器里找到实时便笺添加管理员权限运行 没用 删除本日日志 没有发现报错时有重新生成
> > 在替换文件直接打开 KeqingNiuza.RealtimeNotes.exe 添加成功后 取消磁贴 用启动器打开主程序（发现更新了6m的文件）打开实时便笺 添加磁贴 还是会报同样的错
> > 再然后 重新直接打开KeqingNiuza.RealtimeNotes.exe 添加磁贴 报错 重新把补丁文件覆盖bin目录后 重新打开 KeqingNiuza.RealtimeNotes.exe 添加磁贴 还是报错 把自己试废了 ![GIF](https://user-images.githubusercontent.com/57703506/139883460-783ec783-3ba4-4e0e-bedc-c02092fafccf.gif)
> 
> 你可以试试用Dism++先把之前安装的keqing开头的appx卸载了再添加，我试了几次都是可以的

不太行  注册程序包删除后 重新覆盖打开后 重新注册后 再固定成这样了
![图片](https://user-images.githubusercontent.com/57703506/139893784-74ee9a82-63a1-41b9-9b47-8ae03b22206e.png)

**Comment by Scighost** [comment]
运行启动器时会强制同步所有文件，把之前的覆盖的文件又修改回去了。
我在这个issue中发布的版本只加入了日志的内容，业务逻辑上没有修改。
已经重新生成一遍，不知道有没有问题。

**Comment by Scighost** [comment]
> 不过通过KeqingNiuza.RealtimeNotes.exe添加定时刷新任务时会出现 输入某个时间数字，第一次添加定时任务时： 添加失败：没有注册类 没有注册类。 不改变这个数字，继续点添加定时任务： 添加失败：拒绝访问。（异常来自HRESULT:0x80070005(E_ACCESSDENIED)） Orz

可以尝试使用管理员权限启动

**Comment by wuhan890809** [comment]
辛苦了。刚刚我也遇到了和 @nek0us 一样的问题，就是添加磁贴之后取消，进主程序继续报错，回到KeqingNiuza.RealtimeNotes.exe之后也报错。
Log附上
[note-211103.txt](https://github.com/Scighost/KeqingNiuza/files/7462627/note-211103.txt)
之后我执行了如下步骤
1、运行里输入certlm.msc，从受信任的根证书颁发机构里找到这个证书删除。
2、Dism++卸载相关appx
3、删除bin、Log和UserData文件夹
4、运行Launcher下载组件，程序打开之后，点击设置，点一下“开始游戏前提醒”，这时候会弹出一个未将对象引用设置到对象实例的错误，虽然之前觉得这个错误很烦，但是这次多亏了它创建了Log文件，之后运行KeqingNiuza.RealtimeNotes.exe会少一次报缺少Log的错误。
5、下载ticket里面的压缩包覆盖bin内的文件
6、重新安装证书。
7、管理员运行KeqingNiuza.RealtimeNotes.exe，重新注册程序包，成功；重新录入cookie，成功；重新设置定时任务，成功；点击固定到开始屏幕，失败。
8、关闭KeqingNiuza.RealtimeNotes.exe，点开同层的KeqingNiuZa.exe，点击设置-实时便笺-点击固定到开始屏幕，成功，磁贴出现。自动更新也正常。

**Comment by Scighost** [comment]
现在可以确定问题出现在**请求固定磁贴**那一行，但是根据错误信息无法判断具体原因（根本判断不了）

**Comment by Aniverse** [comment]
我也是一样的情况，看到上边一串讨论一时半会儿都懒得尝试解决了←_←  

提个建议，能否考虑做成任务栏右下角显示树脂？类似这样子：  
![example](https://i0.hdslb.com/bfs/album/f06d565403da1c133424c1575e18ca651484ff4b.png)  
不过这样子就只显示树脂（最重要的其实也就是树脂） ，更多的信息我觉得可以设计成右键弹出的菜单里显示？

**Comment by Scighost** [comment]
> 我也是一样的情况，看到上边一串讨论一时半会儿都懒得尝试解决了←_←
> 
> 提个建议，能否考虑做成任务栏右下角显示树脂？类似这样子： ![example](https://camo.githubusercontent.com/87b9c9d04f4c9dc0c5c14ba450d808e0a77a017822a214ca6be1a6833e639c47/68747470733a2f2f69302e6864736c622e636f6d2f6266732f616c62756d2f663036643536353430336461316331333334323463313537356531386361363531343834666634622e706e67) 不过这样子就只显示树脂（最重要的其实也就是树脂） ，更多的信息我觉得可以设计成右键弹出的菜单里显示？

能力不够，做不到[]~(￣▽￣)~*

**Comment by Scighost** [comment]
重新给「实时便笺」功能做了一个完整的安装包，稀疏包无法使用的可以去下载
https://github.com/Scighost/KeqingNiuza/releases/tag/v2.2.0

**Comment by Scighost** [comment]
#80
