### ISSUE TITLE
记录遗漏

### ISSUE THREAD

**Issue by linningmii** [Scighost/KeqingNiuza#40]
游戏内数据祈愿历史是全的。

删除已有用户数据后重新加载数据后正常

个人猜测是牛杂店更新时从官方API call到的数据不全，然后官方数据正常后阿晴只从最新的记录时间戳处做了更新，导致没有更新之前缺少的数据？

问题确认，删除数据样本

**Comment by fmaples** [comment]
米哈游服务器的问题，你可以自己进入祈愿历史界面查看，官方数据是错误的。等明日官方数据库恢复吧。

**Comment by BladeandSoulLyn** [comment]
我是昨晚6点左右抽卡，晚上8点半左右开始用软件拉取数据的😮刚刚点开软件的时候才看到更新提醒说昨晚的数据出错了，肿么回事

**Comment by linningmii** [comment]
感觉还是可以对近六个月数据做全量更新？没有必要从最后的时间戳开始，对于大氪佬来说也就万把条数据，这个数据量算起来应该是没有多少负担的

**Comment by Lightczx** [comment]
@Scighost 比较简单的solution就是全量获取然后把之前获取的记录裁剪后接上去

**Comment by Scighost** [comment]
把本地记录删掉就可以全量更新了（狗头

**Comment by Lightczx** [comment]
这样6个月前的数据就没了

**Comment by Scighost** [comment]
不是有个导入功能嘛，2.2.0.1的更新提示里写了操作过程

**Comment by Lightczx** [comment]
好家伙，用户的头发换程序员的头发😂
