### ISSUE TITLE
建议新增一种任务提醒的计时类型，下次提醒时间为第 N 天的 N 点钟

### ISSUE THREAD

**Issue by Aniverse** [Scighost/KeqingNiuza#44]
在 2.0 版本以后，水晶矿和魔晶矿的刷新时间从 72 小时改为刷新后第三日服务器时间 0:00；
此外，像每周找 NPC 买圣遗物狗粮是固定每周四 04:00 刷新的；  

因此希望有这么一个类型的提醒设定：比如挖矿，我按了重置按钮以后，时间会重置成第三天的 8:00；比如买狗粮，我按了重置后，时间重置为第七天后的 8:00。  
这两种都是同一种类型的倒计时，即用户设定两个变量：
① 间隔天数 A，设定为 1 就是第二天，设定为 2 就是第三天；
② 几点提醒 B，比如 04:00 或者 08:00；
比如 A=2，B=04:00，就是第三天的 4 点提醒，且按了重置按钮以后也会把下次提醒时间重置为第三天 4 点  

当然，这个需求目前靠修改计时里的“下次触发时间”也可以做到，但稍显麻烦

**Comment by Scighost** [comment]
感谢建议，~~没想到还真有人每天使用这个功能~~
建议的功能已完成，但是下一版本计划中的内容还有部分正在进行中，暂时不会发布（不会等很久）

**Comment by Aniverse** [comment]
话说你是不是忘记发布 release 了，还是要等 2.3.0 再发布？  
大多数人是没有能力自己编译的，即便不发布新的 release，也可以更新一下 2.2.0 release 里的附件

**Comment by Scighost** [comment]
2.2.1版本，11月13号11点发布
https://github.com/Scighost/KeqingNiuza/blob/main/ChangeLog.md#221-21111311

**Comment by Aniverse** [comment]
> 2.2.1版本，11月13号11点发布 https://github.com/Scighost/KeqingNiuza/blob/main/ChangeLog.md#221-21111311

更新日志我是看到了的，我指这里的 [release](https://github.com/Scighost/KeqingNiuza/releases)，现在源码更新了，但是用户最后使用的是二进制文件啊

**Comment by Aniverse** [comment]
噗，我之前是创建了一个 KeqingNiuza\bin\KeqingNiuza.exe 的快捷方式到桌面上，都是这么打开的，所以我不知道在哪里更新  
你这么说了以后我打开了 KeqingNiuza\KeqingNiuza Launcher.exe 就自动更新到 2.2.2 了，那没事了
