### ISSUE TITLE
忽略第一个五星希望只不显示抽数而不直接隐藏该五星

### ISSUE THREAD

**Issue by Yinr** [Scighost/KeqingNiuza#46]
在我看来“忽略第一个 5 星”是因为历史数据没有保存的情况下为了统计抽数的准确性没办法的操作。
目前选择“忽略第一个 5 星”之后会直接在主界面的 5 星记录里隐藏了第一个五星，然而我感觉还是希望能一眼就看到所有抽到的五星，知道自己之前抽出过啥。所以希望“隐藏第一个 5 星”之后记录里的第一个五星还是会显示在主界面，只是不显示抽数或者抽数用特定字符代替。

**Comment by Scighost** [comment]
好建议！
然而没做出来，计算的时候就很麻烦，所以选择了现在的方案。

**Comment by Yinr** [comment]
看了看代码，我的想法是在 [WishSummary.cs#L124](https://github.com/Yinr/KeqingNiuza/blob/723ab096691ebfa3147a5fb4a4f5ede8648073f3/src/KeqingNiuza.Core/Wish/WishSummary.cs#L124) 之前把第一个五星的数据另存出来，并用 `GetStatistics` 统计之后插入到 [`ws.Star5List`](https://github.com/Yinr/KeqingNiuza/blob/723ab096691ebfa3147a5fb4a4f5ede8648073f3/src/KeqingNiuza.Core/Wish/WishSummary.cs#L149) 开头。
没用过 Visual Studio/C#，不知道这样可不可行🤣... Fork 了然后在 vs 里稍微改了一下发现不知道怎么跑起来 2333

**Comment by Yinr** [comment]
啊 不对 我跑起来了，直接加到开头会影响统计...我再试试

**Comment by Scighost** [comment]
加油 ( •̀ ω •́ )✧

**Comment by Yinr** [comment]
改好了~因为没用过 C# 所以就不 pr 了，测试了一下应该没问题，就提供一个参考~
[修改内容在这里](https://github.com/Yinr/KeqingNiuza/commit/5a684dbedb699d2d056631072567ff8b235ba613)

![image](https://user-images.githubusercontent.com/9482504/142761419-42575617-9051-493f-841f-86420d2dffff.png)

**Comment by Scighost** [comment]
感谢您的贡献，已合并
