### ISSUE TITLE
您好，能不能做个实时便笺在win11上显示的功能

### ISSUE THREAD

**Issue by czwzy2017** [Scighost/KeqingNiuza#47]
win11取消了磁贴，能不能做个比如桌面小工具之类的，显示实时便签。

**Comment by Scighost** [comment]
给你指个路 https://github.com/DGP-Studio/Snap.Genshin

**Comment by czwzy2017** [comment]
> 给你指个路 https://github.com/DGP-Studio/Snap.Genshin

谢谢
