### ISSUE TITLE
2.3版本更新后，加载祈愿数据时显示遇到错误

### ISSUE THREAD

**Issue by mentoschow** [Scighost/KeqingNiuza#48]
重复了很多次依旧显示错误，请问是什么问题？
![微信图片_20211124141856](https://user-images.githubusercontent.com/75648530/143179300-af4b241c-82ef-4b44-909b-7a13cbc4fdc9.png)

**Comment by Scighost** [comment]
已经解决，马上发新版本

**Comment by mentoschow** [comment]
谢谢！
