### ISSUE TITLE
关于祈愿记录备份的三个小问题（不是坚果云的

### ISSUE THREAD

**Issue by yzyzy1234** [Scighost/KeqingNiuza#49]
1. 新增的祈愿记录备份功能是备份到刻记牛杂的服务器上吗？
2. 下载备份的时候还需要自己通过json导入数据吗？
3. 其他端同步数据只需要uid一致就可以下载吗？

**Comment by Scighost** [comment]
1 是的
2 是的
3 uid一致可下载、上传、删除，现在只有PC版，没有其他端

**Comment by yzyzy1234** [comment]
非常感谢！


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月24日(周三) 下午2:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Scighost/KeqingNiuza] 关于祈愿记录备份的三个小问题（不是坚果云的 (Issue #49)




 
1 是的
 2 是的
 3 uid一致可下载、上传、删除，现在只有PC版，没有其他端
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
