### ISSUE TITLE
对301和400的保底数计算混乱

### ISSUE THREAD

**Issue by TremblingMoeNew** [Scighost/KeqingNiuza#50]
要我说完全没必要分开算，毕竟本质上就是同一个池子（手动神里扇子脸.jpg）
这保底是算分开了吗
![211124-未标题-1](https://user-images.githubusercontent.com/39522864/143219873-7ba9aba2-c726-4a6f-be34-15521ed76d5a.png)
![211124-未标题-2](https://user-images.githubusercontent.com/39522864/143219881-79ccc119-9c23-4f5d-a669-ebd984472c54.png)

**Comment by TremblingMoeNew** [comment]
另外祈愿活动选这次的这俩池子时，400池的那条记录也无法显示出来，只有301的那条被筛出来了

**Comment by Scighost** [comment]
适配了但没完全适配（🤣

**Comment by TremblingMoeNew** [comment]
![211124-未标题-3](https://user-images.githubusercontent.com/39522864/143234874-566befd3-544c-48b6-99d8-b2ff385bb59d.png)
适配了，但依然没完全适配
![QQ图片20211124200142](https://user-images.githubusercontent.com/39522864/143234837-e5bfe7ac-ffeb-4877-8e84-ec0f28fba224.jpg)

**Comment by Scighost** [comment]
我tm直呼好家伙，今天要狂刷版本号了🤣
