### ISSUE TITLE
导入6个月前的记录，新手祈愿无法导入

### ISSUE THREAD

**Issue by fkfkfk576** [Scighost/KeqingNiuza#51]

**Comment by fkfkfk576** [comment]
![image](https://user-images.githubusercontent.com/94972162/143243678-3e075a9a-724b-455f-aead-75c27f4081d0.png)
![image](https://user-images.githubusercontent.com/94972162/143243710-abfcfaf9-f894-4e28-9151-f6368df1dc63.png)

**Comment by fkfkfk576** [comment]
导入列表中已经读取到，点击【导入】，显示导入成功，但是数据中没有获取到

**Comment by Scighost** [comment]
重启一下试试

**Comment by fkfkfk576** [comment]
还是不行，上个版本还可以的，第二次打开自动更新了，然后就不行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Scighost/KeqingNiuza"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月24日(星期三) 晚上9:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Scighost/KeqingNiuza] 导入6个月前的记录，新手祈愿无法导入 (Issue #51)





 
重启一下试试
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Scighost** [comment]
你把文件发个我吧
scighost@outlook.com

**Comment by Scighost** [comment]
刚才检查了下代码，发现是下午修bug的时候把新手祈愿相关的代码删掉了；
你的导入操作没有问题，新手祈愿的数据已经保存了，只是没有展示出来。

**Comment by Scighost** [comment]
> 刚才检查了下代码，发现是下午修bug的时候把新手祈愿相关的代码删掉了； 你的导入操作没有问题，新手祈愿的数据已经保存了，只是没有展示出来。

这个确实是我的个人失误，会丢失「新手祈愿」记录，已在2.2.2.2版本修复。
