### ISSUE TITLE
反馈四星武器「曚云之月」与「断浪长鳍」图标缺失和角色祈愿2未能在角色详情中显示的问题

### ISSUE THREAD

**Issue by BladeandSoulLyn** [Scighost/KeqingNiuza#55]
开发者辛苦了！反馈一下两个问题！
1：两个新四星武器图标缺失。
![1](https://user-images.githubusercontent.com/93634398/143666542-dabd8799-f646-41fb-a853-b307a29d23e8.png):
2：点击某个角色查看详细历史数据时，在角色祈愿2池子中得到的角色未能显示。如图我在本次优菈池歪了卢姥爷（真是个悲伤的故事）但是点进去后没有显示该池子数据。
![2](https://user-images.githubusercontent.com/93634398/143666686-5130b002-a251-42cd-97fa-5f9a0215b72b.png)

**Comment by Scighost** [comment]
第二张图的页面确实还没改，老早前写的代码，现在看搞不清楚写的什么了 _(:з」∠)_

**Comment by Klamist** [comment]
我都没看过第二个页面……这怎么进去的

**Comment by Scighost** [comment]
> 我都没看过第二个页面……这怎么进去的

随便点一个角色或武器的图片。
