### ISSUE TITLE
祈愿数据有随机丢失问题

### ISSUE THREAD

**Issue by CrescentLove** [Scighost/KeqingNiuza#56]
大概70发丢了十发的数据，GUI界面的数据列表和我原神祈愿记录对不上

**Comment by Scighost** [comment]
丢失了哪一段时间的记录？
如果是新手池，那确实是我几天前的失误；
如果是胡桃池第一天，是米哈游服务器的问题；
如果是其他时间段，再反馈一下详细信息。

**Comment by CrescentLove** [comment]
OK是胡桃第一天，服务器问题
