### ISSUE TITLE
可以支持外服吗？

### ISSUE THREAD

**Issue by gabriel254** [Scighost/KeqingNiuza#6]
用国服账号试用了一下，非常好用，比之前那种导出excel再上传到网站上显示方便多了。但我发现这个似乎并不支持外服账号，我登录外服账号后，执行 `更换UID > 添加UID > 加载数据` 之后，还是加载了刚才国服的数据，希望可以支持外服客户端。

细节说明：我是在一台电脑上同时安装了原神国服和国际服的客户端。安装第一个国服客户端时，安装路径默认是在`C:\Program Files\Genshin Impact`。如果想在同一台机器上同时安装国际服客户端，需要在安装国际服客户端时手动修改安装路径，比如改成`C:\Program Files\Genshin Impact USA`，否则会覆盖掉之前安装的国服客户端。不知道这款软件是本身就不支持外服账号还是说只会加载安装到默认路径`C:\Program Files\Genshin Impact`下的原神客户端？
还有一个路径相关的信息是，国服的数据文件在`C:\Users\用户名\AppData\LocalLow\miHoYo\原神\output_log.txt`，外服的在`C:\Users\用户名\AppData\LocalLow\miHoYo\Genshin Impact\output_log.txt`

**Comment by Scighost** [comment]
当初写代码的时候没有考虑这么多，软件的功能和国服卡池时间有很强的相关性，即使读取了外服的数据也有可能因为卡池时间对不上导致出错。我现在暂时没有精力修改这个问题，推荐使用支持外服的[Genshin  Wish Export](https://github.com/biuuu/genshin-wish-export)，但是这个会忽略祈愿数据中的有用信息，如果需要保存从网页上爬取的所有数据，推荐使用[gacha-wish-export](https://github.com/sunfkny/genshin-gacha-export)。
