### ISSUE TITLE
进入之后闪退，在下载文件界面

### ISSUE THREAD

**Issue by yongfeng0719** [Scighost/KeqingNiuza#63]
[launcher-211221.txt](https://github.com/Scighost/KeqingNiuza/files/7749017/launcher-211221.txt)
版本是2.2，双击打开KeqingNiuza Launcher.exe之后，还没开始下载文件就闪退了，exe文件自动移到了delete目录
log文件已经上传了，请看看这是啥问题，是不是我电脑缺少啥环境

**Comment by xixky** [comment]
@Scighost 
![2021_12_21_1403×784_09889cd9-967e-494a-b5f5-339185222b71](https://user-images.githubusercontent.com/21142462/146858455-3fe0f889-a1d2-4b98-b8a6-ae245d9fe85e.png)

更新使用的jsdelivr在中国已经停止服务

**Comment by xixky** [comment]
出错文件
https://cdn.jsdelivr.net/gh/Scighost/KeqingNiuza@cdn2/obj/6/6F05E55D46FCDF20FD1DF413241072B0110B3CFD4053C4C8C93C194B081CFE98

**Comment by Scighost** [comment]
大坑啊，还得重新找个cdn _(:3」∠)_

**Comment by yongfeng0719** [comment]
= = 难受啊大佬

**Comment by Scighost** [comment]
> = = 难受啊大佬

更新源已经换了，国内速度应该没问题，国外不知道。

**Comment by yongfeng0719** [comment]
> > = = 难受啊大佬
> 
> 更新源已经换了，国内速度应该没问题，国外不知道。

我试了一下，可以了，感谢！！！

**Comment by gqzcl** [comment]
> > = = 难受啊大佬
> 
> 更新源已经换了，国内速度应该没问题，国外不知道。

国内可以，但是国外是503

**Comment by Scighost** [comment]
> 国内可以，但是国外是503

又换了个新的下载源，应该能用吧。

**Comment by gy6221** [comment]
全局梯子，遇到更新时429错误
能否提供个参数可以不走CDN？

**Comment by Scighost** [comment]
> 全局梯子，遇到更新时429错误
> 能否提供个参数可以不走CDN反代，直接从github拖？

梯子倒是不需要，除非翻回大陆。

**Comment by gy6221** [comment]
按我的理解，这个429是fastly cdn返回的错误吧
如果不用fastly，直连github(如果网络环境允许)应该能没那么频繁遇到？

或者在下载器里增加遇到429延时重试的逻辑
