### ISSUE TITLE
实时便笺无法正常使用和米游社签到没有日志

### ISSUE THREAD

**Issue by pbxs666** [Scighost/KeqingNiuza#64]
1.今天突然便笺就无法更新数据了，日志里记录：
```
[21-12-24 15:42:44.208]
System.Net.Http.HttpRequestException: -2147483648 Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   在 DGP.Genshin.Common.Request.DynamicSecret.RequesterExtensions.<GetWhileUpdateDynamicSecret2Async>d__0`1.MoveNext() 位置 D:\a\KeqingNiuza\KeqingNiuza\src\KeqingNiuza.RealtimeNotes\DGP.Genshin\Common\Request\DynamicSecret\RequesterExtensions.cs:行号 26
```
…………
尝试关闭米游社里的实时便笺显示，再次刷新，按理应该显示无法获取信息之类的提示(上次就是这个问题，捣鼓半天发现米游社就没开相应功能，最后开启解决)，但还是提示-2147483648 Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
以为是版本过久，打开启动器果真有新版，结果更新2.2.3版后还是这样。cookies也更新过了。
2.签到会提示签到成功，但是不会生成日志，之前每次签到都是有日志记录到TXT的。

**Comment by Mike-green-png** [comment]
同上，我之前的实时便笩动态磁态点击无法进行refresh，而今天我打算进行手动更新的时候发现弹出了如下代码：
{-2147483648 Unexpected character encountered while parsing valve：<. Path ", line 0, position 0.}
上去StackOverflow看到一条差不多的但是不知道怎么解决。
网址就是：https://stackoverflow.com/questions/23259173/unexpected-character-encountered-while-parsing-value

**Comment by Scighost** [comment]
#65
