### ISSUE TITLE
http response 429

### ISSUE THREAD

**Issue by nianyush** [Scighost/KeqingNiuza#66]
rt, 下载安装时报错
版本Launcher 2.2.3
[launcher-211224.txt](https://github.com/Scighost/KeqingNiuza/files/7775095/launcher-211224.txt)

是因为在海外的缘故吗，能不能放个全量包在github上，不需要从cdn下载

**Comment by Scighost** [comment]
这是因为请求过多被限制了，国内外分流还没做出来。
