### ISSUE TITLE
希望可以让演奏的每一首曲子记住自己的升降调

### ISSUE THREAD

**Issue by Rt39** [Scighost/KeqingNiuza#69]
在自动演奏中，每一首曲子由于命中率的不同，需要为每一首曲子手动调节升降调，但这个升降调在所有曲子中是共同的，也就是说如果想弹奏另一首歌曲时调节了升降调，前面所调节的升降调被覆盖，希望每一首曲子的升降调能和曲子一一对应。

另，在关闭某个音轨的时候，会自动跳转到游戏，这样关闭多个音轨就比较麻烦，希望能优化此功能。

**Comment by Scighost** [comment]
记住升降调需要文件保存设置信息，现有的文件已经有很多了，再加会管理不过来。
自动跳转到游戏对应设置**自动跳转到原神窗口**。
