### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Lightczx** [Scighost/KeqingNiuza#7]
代码层面：
像下面这种XAML，在`DataTemplate`里面
``` xaml
<TextBlock FontSize="12" Foreground="{Binding Brush}" Text="{Binding Name}" />
<TextBlock FontSize="12" Foreground="{Binding Brush}" Text="[" />
<TextBlock FontSize="12" Foreground="{Binding Brush}" Text="{Binding Num}" />
<TextBlock FontSize="12" Foreground="{Binding Brush}" Text="]" />

```
可以简化为
``` xaml
<TextBlock FontSize="12" Foreground="{Binding Brush}">
    <TextBlock.Text>
        <MulitBinding StringFormat="{}{0}[{1}]" FallBackValue="">
            <Binding Path="Name"/>
            <Binding Path="Num"/>
        </MulitBinding>
    </TextBlock.Text>
</TextBlock>
```
`FallbackValue`置空,这样在没有数据时不会显示"[]",控件的数量也从4个减少到了1个

---

这里用来显示角色图片的ImageBrush
``` xaml
<Border.Background>
    <ImageBrush ImageSource="{Binding Thumb, Converter={StaticResource ImageConverter}}" />
</Border.Background>
```
最好加上
``` xaml
<Border.Background>
    <ImageBrush 
        ImageSource="{Binding Thumb, Converter={StaticResource ImageConverter}}" 
        RenderOptions.BitmapScalingMode="HighQuality"/>
</Border.Background>
```
尽管渲染速度会变慢，但是图片精细度会高很多，锯齿也能减少

**Comment by Scighost** [comment]
学习了（真有人看我的代码，好高兴

**Comment by Lightczx** [comment]
感觉很多地方都能优化的其实

**Comment by Lightczx** [comment]
希望下个版本能实装图片的锯齿消除，这个看的我头疼

**Comment by Scighost** [comment]
能截个图我看看吗？
我的显示器上 RenderOptions.BitmapScalingMode 属性每个值都尝试过了，几乎看不到有什么区别。

**Comment by Lightczx** [comment]
我试了一下，发现  ```RenderOptions.BitmapScalingMode``` 附加属性只在 ```<Image/>``` 控件上起作用
 ```<Image/>``` 的问题就是做右下角的圆角不好做
不过我还是希望你可以试一下把```<ImageBrush/>```换成```<Image/>```

**Comment by Lightczx** [comment]
```Image```的圆角似乎可以用```<Image.Clip/>```实现

**Comment by Lightczx** [comment]
查了一下 RenderOptions.BitmapScalingMode 需要附加到附加使用Brush的控件上，也就是你的Border

**Comment by Lightczx** [comment]
Before:
![image.png](https://i.loli.net/2021/07/30/eFKRYuvs4TXoanf.png)
After:
![image.png](https://i.loli.net/2021/07/30/w5gTvPNVtsHh9uW.png)

在我的显示器上效果非常显著

**Comment by Lightczx** [comment]
``` xaml
<Border 
    x:Name="ImageBorder" 
    Width="100" 
    Height="100" 
    VerticalAlignment="Top" 
    BorderThickness="0" 
    CornerRadius="0 0 20 0" 
    RenderOptions.BitmapScalingMode="HighQuality">
    <Border.Background>
        <ImageBrush ImageSource="{Binding Thumb, Converter={StaticResource ImageConverter}}" />
    </Border.Background>
</Border>
```

**Comment by Scighost** [comment]
加上`RenderOptions.BitmapScalingMode="HighQuality"`属性后图片确实变得柔和一些，锯齿明显减少了
前后对比
![image](https://user-images.githubusercontent.com/61003590/127626006-f2390a04-4c0d-44fa-b634-7769f9ec17fd.png)
![image](https://user-images.githubusercontent.com/61003590/127626049-556d06ca-890e-48bc-856e-f8d912c12c48.png)

另外，点击头像后，人物全身图片的质量怎么样

前后对比
![image](https://user-images.githubusercontent.com/61003590/127626310-f2f97f30-ea4e-49eb-9ff4-04affdacfed1.png)
![image](https://user-images.githubusercontent.com/61003590/127626455-75da2f5a-1655-437c-9e43-1d8efee94a9b.png)

**Comment by Lightczx** [comment]
全身的这个出于性能考虑可以不加，本身图片够大，在进行小尺度的拉伸后锯齿还是可以接受的
如果要加那最好不过

**Comment by Lightczx** [comment]
我倒是觉得点击进入详细页面的这个功能做的太隐含了，我最开始甚至完全不觉得那些item可以点进去

**Comment by Scighost** [comment]
我觉得问题不大，能用Win10的电脑不差这点儿性能
![image](https://user-images.githubusercontent.com/61003590/127627168-87802966-9778-40ef-abf2-e888f6040a50.png)

这个详细页面本身是突发奇想做出来的，没什么有用信息，也就没有明显的交互提示。
下次重构时会删除这些没啥用的功能，毕竟我自己都不会去看🤣

**Comment by Lightczx** [comment]
详细页面右侧的信息我认为还是蛮有用的，可以保留
另外关于性能方面，主要还是控件数量决定的，控件的加载真的非常的耗算力，非常容易阻塞ui线程

**Comment by Lightczx** [comment]
可以直接把那个页面改成一个小flyout（HandyControl里面应该是Popup?），只包含右侧的文字内容

**Comment by Scighost** [comment]
这个方法不错，记下了

**Comment by Scighost** [comment]
还有修改建议吗，没有的话就我上传更新了
