### ISSUE TITLE
新版本（2.2.5.2）缺少申鹤和云堇的立绘图

### ISSUE THREAD

**Issue by Askwind** [Scighost/KeqingNiuza#70]
抽卡详情中缺少申鹤和云堇的立绘图

**Comment by Scighost** [comment]
图还没出来，我也没办法。
https://genshin-impact.fandom.com/wiki/Shenhe
https://genshin-impact.fandom.com/wiki/Yun_Jin

**Comment by Askwind** [comment]
我倒是自己添加到 \bin\resource\character 目录下，
我是用的这里的图
https://genshin.honeyhunterworld.com/db/char/shenhe/
https://genshin.honeyhunterworld.com/db/char/yunjin/

**Comment by Scighost** [comment]
风格不一致，暂时不加

**Comment by Askwind** [comment]
> 风格不一致，暂时不加

那就等更新吧
