### ISSUE TITLE
2.4版本角色祈愿缺少部分抽卡数据

### ISSUE THREAD

**Issue by TwilightDawn39** [Scighost/KeqingNiuza#71]
如图，缺少申鹤及前后两项武器数据，芭芭拉后三项武器数据也有缺失。log及UserData文件夹在压缩包内
![Snipaste_2022-01-05_21-54-12](https://user-images.githubusercontent.com/43905773/148235615-c811844c-edab-4326-8dcf-7a59f015e18a.png)
![Snipaste_2022-01-05_21-54-22](https://user-images.githubusercontent.com/43905773/148235626-aaa46d74-fd07-40e9-857f-a9b63919a693.png)
![Snipaste_2022-01-05_21-54-30](https://user-images.githubusercontent.com/43905773/148235631-cfbf7c25-5ab1-4463-8351-f383ebe57987.png)
![Snipaste_2022-01-05_22-38-24](https://user-images.githubusercontent.com/43905773/148235633-c968e21f-86f1-4163-bd31-854270da762a.png)
[KeqingNiuza.zip](https://github.com/Scighost/KeqingNiuza/files/7815603/KeqingNiuza.zip)

**Comment by Scighost** [comment]
没搞懂，数据缺失应该重新获取啊

**Comment by TwilightDawn39** [comment]
> 

应该是点右上角头像那儿加载数据吧（平均两个版本才会抽次卡已经忘了怎么用了 :(
如果是加载数据那个按钮的话已经点了好几次了（12点抽卡数据刚出来的时候，下午2点，晚上10点截图的时候）

点加载数据的时候不是会显示正在读取XX池子XX页么，今天第一次点的时候我看它一直读到十几页（因为好久没有用软件读取数据）。发现没有申鹤的数据之后我再点加载数据，我发现软件只会读每个池子的第一页。我以为是因为没有新的抽卡数据所以不往后读取，所以在2点39进行了一次单抽，结果软件还是只读取第一页数据=-= 所以是不是软件读取到本地已有的第一个数据后就不往后读取了啊(不懂程序，小心翼翼的怀疑一下)

**Comment by Scighost** [comment]
没毛病，加载到本地已有的最后一条时就结束；
第一次加载时出现了问题，没有申鹤，但是有了申鹤之后的数据；
暂时没有全量加载功能，可以把你的记录文件**wishlog_{你的uid}.json**移出UserData文件夹，重新加载后再从关于页面导入之前的数据。

**Comment by TwilightDawn39** [comment]
感谢您的解答，我发现是我网络的问题。第一次删除数据后依然没有申鹤的数据，第二次使用手机热点加载出来了
