### ISSUE TITLE
角色卡池2抽出角色的详情界面未显示来源信息

### ISSUE THREAD

**Issue by Viel0320** [Scighost/KeqingNiuza#72]
![image](https://user-images.githubusercontent.com/12400928/148354332-9ebc145a-3153-4825-96cd-62f320a004d3.png)
如图

**Comment by Scighost** [comment]
是这样的，我已经找不到该修改的地方了

**Comment by Viel0320** [comment]
> 是这样的，我已经找不到该修改的地方了

如果官网的记录没有分出字段的话，我觉得两个角色池可以当做一个池子进行处理，我个人反正是无所谓的

**Comment by Viel0320** [comment]
哦我看到其他人已经提过类似的问题了，那这个可以close了
