### ISSUE TITLE
大小保底错误

### ISSUE THREAD

**Issue by klrito123** [Scighost/KeqingNiuza#76]
池子开之前垫了小保底  开了池子大保底出的
![4K`9V(IFJSNWE6IQAVMHHIL](https://user-images.githubusercontent.com/45893413/151280486-73f5d7a1-7dfd-46e2-b5dc-f3600e2eb7a5.png)
![XK3W$SFUGL@CUKOP 39VJ~K](https://user-images.githubusercontent.com/45893413/151280499-e4de2713-e97e-4dc5-962e-1947a257cadf.png)

**Comment by Scighost** [comment]
这个页面可能不会再改了，找不到下手的地方
