### ISSUE TITLE
建议更新实时便笺的显示内容，更改浓缩树脂为洞天宝钱

### ISSUE THREAD

**Issue by pbxs666** [Scighost/KeqingNiuza#78]
先在这里提前祝作者大大新年快乐！！！

如图，现在米游社的“我的角色”板块已经更新了数据的显示类别，取消了浓缩树脂，改为了洞天宝钱的数量，那么咱们的“牛杂店”是不是该更新下啊😊
![image](https://user-images.githubusercontent.com/47630168/151535616-bee0fe4d-1a11-41b6-a7ed-37995a4bf310.png)

我只是说说，这个功能不急，有时间了再做就行。
当下还是要好好享受假期和春节啊。

**Comment by Scighost** [comment]
#80 这里有你要的洞天宝钱
