### ISSUE TITLE
希望能给提醒功能自定义设置提前时间

### ISSUE THREAD

**Issue by kuusei** [Scighost/KeqingNiuza#8]
目前是在倒计时结束/恢复满时提醒。
希望能够加入提前几个小时/天，离恢复满还差多少个这样的设置。
很多提醒需要有一定的提前量，比如深渊和体力，到点后就不太来得及了。
ps：我目前利用手动设置提前量的方式实现，但是会影响使用重置功能

**Comment by Scighost** [comment]
这个功能不适合深渊这种重置时间点固定不变的情况。
关于提前量，你把体力上限设置为150不就提前了一个多小时嘛（懒癌发作中
