### ISSUE TITLE
关于祈愿网址的获取

### ISSUE THREAD

**Issue by weijiang1994** [Scighost/KeqingNiuza#86]
可以请教一下祈愿网址是通过什么方式获取的吗？

**Comment by Scighost** [comment]
日志文件
国服在这个地方 AppData\LocalLow\miHoYo\原神\output_log.txt；
外服在这个地方 AppData\LocalLow\miHoYo\Genshin Impact\output_log.txt；
正则匹配这个语句 OnGetWebViewPageFinish:(.+#/log)

**Comment by weijiang1994** [comment]
> OnGetWebViewPageFinish

牛蛙，原来是这样啊，这几天我一直尝试着用抓包的方式去获取，奈何HTTPS加密传输，获取不到，万分感谢~ 👍
