### ISSUE TITLE
考不考虑直接加入webdav备份

### ISSUE THREAD

**Issue by Shu-Yibin** [Scighost/KeqingNiuza#9]
能不能考虑直接加入webdav备份

**Comment by Scighost** [comment]
你是指自己输入webdav服务商的网址？

**Comment by Shu-Yibin** [comment]
> 你是指自己输入webdav服务商的网址？

是的，因为坚果云也是用的webdav做管理，但我自己是想往群晖的webdav去备份

**Comment by Scighost** [comment]
已更新，cdn缓存要等几个小时才能刷新
