### ISSUE TITLE
播放抽卡BGM希望增加音频通道自定义

### ISSUE THREAD

**Issue by a85418425** [Scighost/KeqingNiuza#92]
![QQ图片20220224095922](https://user-images.githubusercontent.com/77822042/155442947-d18cf55d-b198-4cd0-b5a6-99bb13e01c90.png)

**Comment by a85418425** [comment]
默认的音频通道没声音，可能是因为我有独立声卡。

**Comment by Scighost** [comment]
没有播放音乐这个功能
