### ISSUE TITLE
关于下载地址 CDN 的备用方案

### ISSUE THREAD

**Issue by Nikaple** [Scighost/KeqingNiuza#96]
1. Gitee 等提供 Pages 服务的代码托管服务商

按照官方文档，开通 Pages 服务，然后将下载包上传到 Repo 中即可。例如：
Repo URL: https://gitee.com/nikaple/iwbt-nikaple-engine-doc/blob/master/docsify.min.js

在下载更新包的场景下，用以下两种 URL 应该都可以：
	- Repo Raw: https://gitee.com/nikaple/iwbt-nikaple-engine-doc/raw/master/docsify.min.js
	- Pages: https://nikaple.gitee.io/iwbt-nikaple-engine-doc/docsify.min.js

Pages 的优势主要是能够返回正确的 `Content-Type` 头，不过在下载更新包这个场景下这两种方式应该是一样的。如果用 `Repo Raw` 的方式来管理链接，也可以用 tag 来做版本管理

2. 各大云厂商的对象储存服务

优势主要是能自定义域名，然后上传/下载通过客户端比较方便，个人用户一般都有一些免费的额度，例如我的：
![image](https://user-images.githubusercontent.com/24775744/158001135-c2a634ce-8a12-4207-bbc4-63b6ccc7ec14.png)

当然，缺点显然是流量超了的话就变成按量付费了，只适合小型个人用户白嫖

**Comment by Scighost** [comment]
- 使用 Gitee Raw 不登陆时无法下载较大文件
- 曾经用过自费CDN，不到3天就把当月免费的流量包用完了

这是本项目的CDN统计数据，数据量有些问题，仅供参考
https://www.jsdelivr.com/package/gh/Scighost/KeqingNiuza

**Comment by Nikaple** [comment]
使用一些包管理器应该也行？例如在 JS 社区这边一般是：
1. 先把包上传到 [NPM](http://npmjs.com/)
2. 通过 `cnpm sync [package]` 同步到[国内镜像](https://npmmirror.com/)
3. 用户使用国内镜像下载，这种方案应该就没有流量限制了，并且对国内用户网络也比较友好

**Comment by Scighost** [comment]
本项目的自动更新使用的不是完整安装包，而是分散的小文件，目前只有用cdn比较合适。
